/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interaces;

import Modelo.LigaAjedrez;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author vicen
 */
public class JFrameEditJugador extends javax.swing.JFrame {
    
    JFrame frame;
    LigaAjedrez liga;
    JComboBox clubesBox;
    
    /**
     * Creates new form JFrameEditJugador
     */
    public JFrameEditJugador(JFrame j, LigaAjedrez la) {
        frame = j;
        liga = la;
        initComponents();
        llenarDatos();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNom = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelClub = new javax.swing.JLabel();
        jButtonAtras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        jTextFieldFecha = new javax.swing.JTextField();
        jButtonResponsable = new javax.swing.JButton();
        textoClub = new javax.swing.JTextField();
        cambiarClub = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCategoria = new javax.swing.JTextField();
        jTextFieldElo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListClubes = new javax.swing.JList<>();
        jTextFieldContrasenya = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Modificar datos de jugador");

        jLabelNom.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelNom.setText("Nombre:");

        jTextFieldNombre.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jTextFieldNombre.setEnabled(false);
        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });

        jLabelClub.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelClub.setText("Club:");

        jButtonAtras.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButtonAtras.setText("ATRAS");
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Contraseña:");

        jLabelFecha.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelFecha.setText("Fecha de nacimiento:");

        jTextFieldFecha.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jTextFieldFecha.setText("dd/mm/YY");
        jTextFieldFecha.setEnabled(false);

        jButtonResponsable.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonResponsable.setText("Responsable");
        jButtonResponsable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResponsableActionPerformed(evt);
            }
        });

        textoClub.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        textoClub.setEnabled(false);
        textoClub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoClubActionPerformed(evt);
            }
        });

        cambiarClub.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cambiarClub.setText("Cambiar Club");
        cambiarClub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarClubActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setText("Cambiar Contraseña");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("ELO:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Categoria:");

        jTextFieldCategoria.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldCategoria.setEnabled(false);

        jTextFieldElo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextFieldElo.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("CLUBES HISTORICO");

        jListClubes.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jScrollPane1.setViewportView(jListClubes);

        jTextFieldContrasenya.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jTextFieldContrasenya.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAtras)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabelNom)
                            .addComponent(jLabelClub)
                            .addComponent(jLabelFecha)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldElo)
                                    .addComponent(jTextFieldCategoria)
                                    .addComponent(textoClub)
                                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(jTextFieldContrasenya))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cambiarClub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonResponsable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNom)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jTextFieldContrasenya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoClub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelClub)
                    .addComponent(cambiarClub))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFecha))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonResponsable)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldElo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(36, 36, 36)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButtonAtras)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        this.setVisible(false);
        frame.setVisible(true);
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jButtonResponsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResponsableActionPerformed
        /*JFrameRegistrarResponsable responsable = new JFrameRegistrarResponsable(this);
        responsable.setVisible(true);*/
    }//GEN-LAST:event_jButtonResponsableActionPerformed


    private void cambiarClubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarClubActionPerformed
        String selector = (String)JOptionPane.showInputDialog(this, "Selecciona el nuevo club","Cambiar club jugador", JOptionPane.QUESTION_MESSAGE, null, liga.listaClubes().toArray(),"Selecciona club: ");
       
        if(selector!=null) {
            float cuota = liga.cambiarClub(selector);
            JOptionPane.showMessageDialog(this, "La cuota mensual que debe pagar ahora es de "+cuota);
            llenarDatos();
        }
    }//GEN-LAST:event_cambiarClubActionPerformed

    private void textoClubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoClubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoClubActionPerformed

    private void llenarDatos() {
        String [] datos = liga.datosJugador().split("-");
        jTextFieldNombre.setText(datos[0]);
        jTextFieldContrasenya.setText(datos[1]);
        textoClub.setText(datos[2]);
        jTextFieldFecha.setText(datos[3]);
        
        anyadirTorneos();
    }
    
    private void anyadirTorneos(){
        ArrayList<String> clubes = liga.listaClubesHistorico();
        
        if (clubes.size()>0){
            String [] lista = new String[clubes.size()];
            for(int i=0;i<clubes.size();i++)
                lista[i]=clubes.get(i);
            jListClubes.setListData(lista);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cambiarClub;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonResponsable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelClub;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JList<String> jListClubes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldCategoria;
    private javax.swing.JTextField jTextFieldContrasenya;
    private javax.swing.JTextField jTextFieldElo;
    private javax.swing.JTextField jTextFieldFecha;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField textoClub;
    // End of variables declaration//GEN-END:variables
}
