/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interaces;

import Modelo.LigaAjedrez;
import javax.swing.JFrame;

/**
 *
 * @author gerar
 */
public class JFrameAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form JFrameAdministrador
     */
    
    JFrame frame;
    LigaAjedrez liga;
    
    public JFrameAdministrador(JFrame l, LigaAjedrez la) {
        initComponents();
        frame = l;
        liga = la;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Salir = new javax.swing.JButton();
        EtiquetaAdministrador = new javax.swing.JLabel();
        JButtonJugadores = new javax.swing.JButton();
        botonClubes = new javax.swing.JButton();
        botonTorneos = new javax.swing.JButton();
        jButtonGerentes = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Salir.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Salir.setText("SALIR");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        EtiquetaAdministrador.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        EtiquetaAdministrador.setText("ADMINISTRADOR DEL SISTEMA");

        JButtonJugadores.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        JButtonJugadores.setText("JUGADORES");
        JButtonJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonJugadoresActionPerformed(evt);
            }
        });

        botonClubes.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        botonClubes.setText("CLUBES");
        botonClubes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonClubesActionPerformed(evt);
            }
        });

        botonTorneos.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        botonTorneos.setText("TORNEOS");
        botonTorneos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTorneosActionPerformed(evt);
            }
        });

        jButtonGerentes.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButtonGerentes.setText("GERENTES");
        jButtonGerentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerentesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonTorneos, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JButtonJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonClubes, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                    .addComponent(jButtonGerentes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EtiquetaAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(EtiquetaAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JButtonJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonClubes, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonTorneos, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(jButtonGerentes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        this.setVisible(false);
        frame.setVisible(true);
    }//GEN-LAST:event_SalirActionPerformed

    private void JButtonJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonJugadoresActionPerformed
        this.setVisible(false);
        JFrameAdminJugadores jugador = new JFrameAdminJugadores(this, liga);
        jugador.setVisible(true);
    }//GEN-LAST:event_JButtonJugadoresActionPerformed

    private void botonClubesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonClubesActionPerformed
        JFrameAdminClubes clubes = new JFrameAdminClubes(this, liga);
        this.setVisible(false);
        clubes.setVisible(true);
    }//GEN-LAST:event_botonClubesActionPerformed

    private void botonTorneosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTorneosActionPerformed
        JFrameAdminTorneos torneos = new JFrameAdminTorneos(this, liga);
        this.setVisible(false);
        torneos.setVisible(true);
    }//GEN-LAST:event_botonTorneosActionPerformed

    private void jButtonGerentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerentesActionPerformed
        JFrameAdminGerentes gerentes = new JFrameAdminGerentes(this, liga);
        this.setVisible(false);
        gerentes.setVisible(true);
    }//GEN-LAST:event_jButtonGerentesActionPerformed


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EtiquetaAdministrador;
    private javax.swing.JButton JButtonJugadores;
    private javax.swing.JButton Salir;
    private javax.swing.JButton botonClubes;
    private javax.swing.JButton botonTorneos;
    private javax.swing.JButton jButtonGerentes;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
