/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interaces;

/**
 *
 * @author vicen
 */
public class JFrameJugador extends javax.swing.JFrame {

    JFrameLogin login;
    
    public JFrameJugador(JFrameLogin l) {
        login = l;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonReserSede = new javax.swing.JButton();
        jButtonAsignResp = new javax.swing.JButton();
        jButtonInfo = new javax.swing.JButton();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelNomUsuario = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonReserSede.setText("Reservar Sede Entrenamiento");

        jButtonAsignResp.setText("Asignar Responsable Infantil");

        jButtonInfo.setText("Ver Información");

        jLabelUsuario.setText("Usuario: ");

        jLabelNomUsuario.setText("Pepito");

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonReserSede)
                    .addComponent(jButtonAsignResp)
                    .addComponent(jButtonInfo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelUsuario)
                        .addGap(11, 11, 11)
                        .addComponent(jLabelNomUsuario))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonSalir)
                        .addGap(15, 15, 15)))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonReserSede)
                    .addComponent(jLabelUsuario)
                    .addComponent(jLabelNomUsuario))
                .addGap(36, 36, 36)
                .addComponent(jButtonAsignResp)
                .addGap(36, 36, 36)
                .addComponent(jButtonInfo)
                .addGap(7, 7, 7)
                .addComponent(jButtonSalir)
                .addGap(79, 79, 79))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        this.setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_jButtonSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAsignResp;
    private javax.swing.JButton jButtonInfo;
    private javax.swing.JButton jButtonReserSede;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelNomUsuario;
    private javax.swing.JLabel jLabelUsuario;
    // End of variables declaration//GEN-END:variables
}
