/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interaces;

/**
 *
 * @author gerar
 */
public class JFrameAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form JFrameAdministrador
     */
    
    JFrameLogin login;
    public JFrameAdministrador(JFrameLogin l) {
        initComponents();
        login = l;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botonReservaSede = new javax.swing.JButton();
        responsableMenores = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        EtiquetaAdministrador = new javax.swing.JLabel();
        consultarInfoTorneos = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonReservaSede.setText("Reservar sede para entrenamiento");
        botonReservaSede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReservaSedeActionPerformed(evt);
            }
        });

        responsableMenores.setText("Añadir responsable para menores");
        responsableMenores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                responsableMenoresActionPerformed(evt);
            }
        });

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        EtiquetaAdministrador.setText("Administrador del Sistema");

        consultarInfoTorneos.setText("Ver información torneos");
        consultarInfoTorneos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarInfoTorneosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(responsableMenores))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(EtiquetaAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(botonReservaSede))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(consultarInfoTorneos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(Salir)))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(EtiquetaAdministrador, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addGap(43, 43, 43)
                .addComponent(botonReservaSede)
                .addGap(34, 34, 34)
                .addComponent(responsableMenores)
                .addGap(63, 63, 63)
                .addComponent(consultarInfoTorneos)
                .addGap(37, 37, 37)
                .addComponent(Salir)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonReservaSedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReservaSedeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonReservaSedeActionPerformed

    private void responsableMenoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_responsableMenoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_responsableMenoresActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        this.setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_SalirActionPerformed

    private void consultarInfoTorneosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarInfoTorneosActionPerformed
        
        
    }//GEN-LAST:event_consultarInfoTorneosActionPerformed


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EtiquetaAdministrador;
    private javax.swing.JButton Salir;
    private javax.swing.JButton botonReservaSede;
    private javax.swing.JButton consultarInfoTorneos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton responsableMenores;
    // End of variables declaration//GEN-END:variables
}
